### ISSUE TITLE
[FR] Preserve list scroll position on item delete

### ISSUE THREAD

**Issue by JC3** [Helfima/helmod#434] opened 2022-10-20 23:37 UTC
Hi;

Currently, when deleting a recipe from a production block, the scroll position of the list is reset to the top.

Would it be possible to preserve the scroll position when an item is deleted?

This would make it a lot easier to delete many recipes from a block with a long list of recipes, since you wouldn't have to re-scroll down from the top every time.

Thanks!!

**Comment by KiwiHawk** [comment] 2022-10-21 03:10
Duplicate of #389

**Closed** 2022-10-21 03:10 UTC
Labels: duplicate
