### ISSUE TITLE
Add an additional function related to beacons.

### ISSUE THREAD

**Issue by Terka128** [Helfima/helmod#449] opened 2023-02-22 15:59 UTC
Hello, I ran into a problem, or rather something similar to it, and I will ask or ask if it is possible to add the function of additional "beacons" to the factory, since there are problems with energy, and I want to calculate everything with efficiency and speed modules at the same time, but there is no such possibility in Helmod, and I have to first to build, and then check that it is not very convenient, especially when additional modifications are installed not only on the buildings, but also on the modules themselves. I hope I made myself clear, since this appeal was translated with the help of an interpreter, thank you in advance. 

![image](https://user-images.githubusercontent.com/126093801/220678804-44e65eb0-bdf1-48cf-99d7-0093126844a0.png)
![image](https://user-images.githubusercontent.com/126093801/220678905-3996b6c5-a803-4cb6-b78a-6cf6683a7bd8.png)

In the screenshot I showed that I would like to add 6 beacons to one factory, which are 5 of them for speed, and one for efficiency (reducing energy consumption), the mod I play with and is shown in the screenshot "Industrial Revolution 3" 

https://mods .factorio.com/mod/IndustrialRevolution3. 

And from the fact that I cannot combine 5 beacons for speed and one for efficiency, I will have to build in a "blind", and then look at what power consumption. Thanks again in advance.

And with Shrovetide(22.02.22)

**Comment by KiwiHawk** [comment] 2023-02-22 23:57
Duplicate of #287

**Closed** 2023-02-22 23:58 UTC
Labels: duplicate, enhancement
