### ISSUE TITLE
Shift left/right click factory & module copy-paste.

### ISSUE THREAD

**Issue by FluffierThanThou** [Helfima/helmod#150] opened 2018-07-20 17:10 UTC
I love Helmod, it's a great help in quickly setting up good ratios, especially with bob and/or angels mods active. 

However, assigning factories and modules to each recipe is a chore, and the interface for it quickly becomes cumbersome. I would love to see the following change;

 - On all relevant dialogs, shift-right clicking a factory or module slot saves the configuration for that slot to the clipboard. 
- if the slot is empty, clear the clipboard.
- On all relevant dialogs, shift-left clicking a factory or module slot pastes the configuration on the clipboard to that slot.
- if the clipboard is empty, clear the slot.

This would allow for much quicker assignment and tweaks of factories/modules across long recipe chains, and make me very happy 🎉

**Comment by Helfima** [comment] 2019-03-26 02:17
Duplicate of #162

**Closed by Helfima** 2019-03-26 02:17 UTC
Labels: enhancement
