### ISSUE TITLE
Close with esc

### ISSUE THREAD

**Issue by CurlyFlow** [Helfima/helmod#339] opened 2021-03-26 01:41 UTC
Someoen already posted it, without a solution.. i dont understand whats the problem, other mods seem to respect it. e.g. FNEI, if i have it open and press esc, just FNEI closes, but the factorio esc screen doenst show... ?

https://github.com/Helfima/helmod/issues/195

The standard is esc, which works, but it also opens the factorio esc menu and at the same time closes helmod.

Is that intentionally? Or whats the issue?!

Can someone close helmod with esc without opening the factorio esc menu at the same time? (maybe this is only a language problem? - im on DE)

**Comment by Helfima** [comment] 2021-03-28 01:08
it's a problem because to do that you set a parameter but if another mod do same that break all and there are other problems
me I use another key, I bind my key on clear cursor :)

**Comment by eihns** [comment] 2021-03-28 10:26
Do you mean the problem is that other mods using esc?

**Comment by eihns** [comment] 2021-03-30 11:21
Do you understand the problem? My english isnt the best...

e.g. FNEI is working perfectly with esc, why helmod not?

**Comment by GuerreroBit** [comment] 2021-12-25 19:59
I guess the mod is not updated anymore(?), but this problem could be fixed by adding "player.opened = frame/windows/theGUIVariable" when the windows is created.
I have been able to fix it in RPG System and Informatron adding it (and key to close the menu), but i couldn't find where the window is created in this mod.

Reference: https://forums.factorio.com/viewtopic.php?f=25&t=77795&p=465594&hilit=esc#p465594
I fix Informatron and RPG System adding these lines:
```
Informatron:
--input:
  {
    type = "custom-input",
    name = "key-close",
    key_sequence = "ESCAPE",
    consuming = "none",
  }
--strings:
  [controls]
  informatron=InformaTron
  close-menu=Close menu
--informatron:
  --Event.addListener(defines.events.on_lua_shortcut, Informatron.on_lua_shortcut)
  Event.addListener("close-menu", function(event) Informatron.close(event.player_index) end)
  --...

  --local main = gui.add{type="frame", name=Informatron.name_window_main, direction="vertical"}
  player.opened = main
  --if not (main and main.valid) then return end




RPGSystem:
--control:
  --tabcharScroll.style.maximal_width = wid - 15
  player.opened = frame
  --update_char_panel(player) 
  
  --script.on_event("key-I", function(event) open_close_char_gui(game.players[event.player_index]) end)
  script.on_event("key-close", function(event) close_char_panel(game.players[event.player_index]) end)
--controls:
  {
    type = "custom-input",
    name = "key-close",
    key_sequence = "ESCAPE",
    consuming = "none",
  }
--locale/en/config:
  [controls]
  key-I=Players Stats
  key-close=Close Menu
```

**Closed** 2024-04-19 21:42 UTC
